### ISSUE TITLE
"Simplification" breaks functionality of ToricVarieties

### ISSUE THREAD

**Issue by HereAround** [kamalsaleh/NConvex#8]
The commit

cd73637222f986b9aab2fd6daff620db982c6f25

changes the order of rays/maximal cones. For example, before this commit we had
Q[x_1,x_2,x_3,x_4]
(weights: [ ( 1, 0 ), ( 0, 1 ), ( 1, 0 ), ( 0, 1 ) ])
 
but now, it says:
Q[x_1,x_2,x_3,x_4]
(weights: [ ( 0, 1 ), ( 1, 0 ), ( 1, 0 ), ( 0, 1 ) ])

Whilst this seems not a big change, a chain of about 30 errors is triggered due to this change in the ToricVarieties package. Also, its functionality is severely influenced (e.g. a test of "IsBasepointFreeDivisor" originally gave true, but now returns false). Likewise, the functionality of my package SheafCohomologyOnToricVarieties (which in turn strongly depends on the output of ToricVarieties) is severely influenced.

Any chance to revert this commit?

Suggestion for the future:
ToricVarieties intricately uses NConvex and CddInterface. Therefore, the tests of the ToricVarieties-package can detect potential flaws in NConvex (as e.g. https://github.com/kamalsaleh/NConvex/issues/5). Hence, my suggestion: Use the tests of ToricVarieties to test NConvex from time to time.

**Comment by kamalsaleh** [comment]
Hello Martin,

The package does not make a specification of the returned lists, hence I would not recommend having assumptions about the order of their elements. I think you made this assumption as you saw in many positions the operator **Set()** applied on a list, which leads to reordering of the entries.

I would not say it breaks the functionality of `ToricVarieties`, since the reason of the error is that the divisor `D` is defined in the test files by `P[1]+P[2]`, so of course any change in the order would affect the list `P` and hence the divisor `D`.

To make the order more predictable I reused the **set()** operator instead of **DuplicateFreeList()** and the tests in `ToricVarieties` should now pass without any warnings.
